# -*- coding: utf-8 -*-
"""LinReg_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/orkhan-amrullayev/23d5000ebae865c5830e3a0b317dcabb/linreg_1.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt

X = 2 * np.random.rand(100, 1)
y = 4+3 * X + np.random.rand(100, 1)

# plt.plot(X, y, "b")   ## it is line plot
plt.plot(X, y, ".b")  #scatter plot

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X, y)

"""## Shows X - as we have just one indeendent variable, amount of output is 1"""

model.coef_

"""## For intercept"""

model.intercept_

"""## both together"""

model.coef_, model.intercept_

